apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-dns-external
  labels:
    app: cis-dns-external
spec:
  selector:
    matchLabels:
      app: cis-dns-external
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cis-dns-external
      annotations:
    spec:
      containers:
      - name: cis-dns-external
        image: mikematera/cis-dns:2020061901
        imagePullPolicy: IfNotPresent
        env:
          - name: DNS_ROLE
            value: "external"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-dns-internal
  labels:
    app: cis-dns-internal
spec:
  selector:
    matchLabels:
      app: cis-dns-internal
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cis-dns-internal
      annotations:
    spec:
      containers:
      - name: cis-dns-internal
        image: mikematera/cis-dns:2020061901
        imagePullPolicy: IfNotPresent
        env:
          - name: DNS_ROLE
            value: "internal"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
