all:
  hosts:
    dell-r630-1:
      ansible_host: 192.168.0.130
      primary_interface: enp131s0f0
      raid_md1_0: /dev/sde 
      raid_md1_0: /dev/sdf 
      raid_md2_0: /dev/sdc 
      raid_md2_0: /dev/sdd 
      device_ssd: /dev/md1
      device_hdd: /dev/md2
      vg_disk_pool_size: 900
      vg_disk_home_size: 200
    supermicro-1:
      ansible_host: 192.168.0.131
      primary_interface: cisnet
    supermicro-2:
      ansible_host: 192.168.0.132
      primary_interface: cisnet
    supermicro-3:
      ansible_host: 192.168.0.140
      primary_interface: rename4
    dell-r620-1:
      ansible_host: 192.168.0.134
      primary_interface: cisnet
      device_ssd: /dev/sda2 
      device_hdd: /dev/sdb
      vg_disk_pool_size: 500
      vg_disk_home_size: 128
    dell-r620-2:
      ansible_host: 192.168.0.135
      primary_interface: cisnet
      device_ssd: /dev/sda2 
      device_hdd: /dev/sdb
    dell-r610-1:
      ansible_host: 192.168.0.136
      primary_interface: cisnet
    dell-r610-2:
      ansible_host: 192.168.0.137
      primary_interface: cisnet
    dell-r610-3:
      ansible_host: 192.168.0.138
      primary_interface: cisnet
  children:
    maas:
      hosts:
        dell-r630-1:
        supermicro-1:
        supermicro-2:
        supermicro-3:
        dell-r620-1:
        dell-r620-2:
        dell-r610-1:
        dell-r610-2:
        dell-r610-3:
    dell-r630:
      hosts:
        dell-r630-1:
    supermicro:
      hosts:
        supermicro-1:
        supermicro-2:
        supermicro-3:
    dell-r620:
      hosts:
        dell-r620-1:
        dell-r620-2:
    dell-r610:
      hosts:
        dell-r610-1:
        dell-r610-2:
        dell-r610-3:
